### ISSUE TITLE
Wav2Letter results

### ISSUE THREAD

**Issue by igormq** [syhw/wer_are_we#15]
Hi,

I saw that the README.md has not included the Wav2Letter yet.

1. https://arxiv.org/pdf/1609.03193.pdf
2. https://arxiv.org/pdf/1712.09444.pdf

Cheers.

**Comment by WilliamTambellini** [comment]
Up to date results from wave2letter++ : 
5% WER on librispeech (Table 2. Decoding performance on LibriSpeech dev-clean)
https://arxiv.org/pdf/1812.07625.pdf
https://github.com/facebookresearch/wav2letter

**Comment by syhw** [comment]
there are some recent/good enough ones
